# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setGeometry(QtCore.QRect(1030, 110, 251, 611))
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setTextVisible(False)
        self.ProgressBar.setOrientation(QtCore.Qt.Vertical)
        self.ProgressBar.setInvertedAppearance(False)
        self.ProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ProgressBar.setObjectName("ProgressBar")
        self.PumpCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.PumpCheckBox.setEnabled(True)
        self.PumpCheckBox.setGeometry(QtCore.QRect(810, 480, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PumpCheckBox.setFont(font)
        self.PumpCheckBox.setObjectName("PumpCheckBox")
        self.StepLabel = QtWidgets.QLabel(self.centralwidget)
        self.StepLabel.setGeometry(QtCore.QRect(20, 30, 781, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.StepLabel.setFont(font)
        self.StepLabel.setObjectName("StepLabel")
        self.TempUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.TempUpButton.setGeometry(QtCore.QRect(810, 310, 201, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.TempUpButton.setFont(font)
        self.TempUpButton.setObjectName("TempUpButton")
        self.TempDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.TempDownButton.setGeometry(QtCore.QRect(810, 400, 201, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.TempDownButton.setFont(font)
        self.TempDownButton.setObjectName("TempDownButton")
        self.PauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PauseButton.setGeometry(QtCore.QRect(810, 530, 201, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.PauseButton.setFont(font)
        self.PauseButton.setObjectName("PauseButton")
        self.SensorLabel = QtWidgets.QLabel(self.centralwidget)
        self.SensorLabel.setGeometry(QtCore.QRect(810, 10, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SensorLabel.setFont(font)
        self.SensorLabel.setText("")
        self.SensorLabel.setObjectName("SensorLabel")
        self.TimeUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.TimeUpButton.setGeometry(QtCore.QRect(810, 110, 201, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.TimeUpButton.setFont(font)
        self.TimeUpButton.setObjectName("TimeUpButton")
        self.TimeDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.TimeDownButton.setGeometry(QtCore.QRect(810, 200, 201, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.TimeDownButton.setFont(font)
        self.TimeDownButton.setObjectName("TimeDownButton")
        self.MainTempLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainTempLabel.setGeometry(QtCore.QRect(1040, 120, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MainTempLabel.setFont(font)
        self.MainTempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTempLabel.setObjectName("MainTempLabel")
        self.TempDownButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.TempDownButton_2.setGeometry(QtCore.QRect(810, 640, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.TempDownButton_2.setFont(font)
        self.TempDownButton_2.setObjectName("TempDownButton_2")
        self.TempDownButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.TempDownButton_3.setGeometry(QtCore.QRect(930, 640, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.TempDownButton_3.setFont(font)
        self.TempDownButton_3.setObjectName("TempDownButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BrewLinker"))
        self.ProgressBar.setFormat(_translate("MainWindow", "%p"))
        self.PumpCheckBox.setText(_translate("MainWindow", "Pumps"))
        self.StepLabel.setText(_translate("MainWindow", "TextLabel"))
        self.TempUpButton.setText(_translate("MainWindow", "↑temp up"))
        self.TempDownButton.setText(_translate("MainWindow", "↓temp down"))
        self.PauseButton.setText(_translate("MainWindow", "Pause"))
        self.TimeUpButton.setText(_translate("MainWindow", "↑ time up"))
        self.TimeDownButton.setText(_translate("MainWindow", "↓time down"))
        self.MainTempLabel.setText(_translate("MainWindow", "TextLabel"))
        self.TempDownButton_2.setText(_translate("MainWindow", "step frem"))
        self.TempDownButton_3.setText(_translate("MainWindow", "step tilbage"))

